version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      roslyn:
        patterns:
          - "Microsoft.CodeAnalysis.*"
      msbuild:
        patterns:
          - "Microsoft.Build.*"
      xunit:
        patterns:
          - "xunit*"

  - package-ecosystem: npm
    directory: /runtime-ts
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
