<Project>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ImplicitUsings>enable</ImplicitUsings>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <PropertyGroup Label="Packaging defaults">
        <Authors>penspanic</Authors>
        <Copyright>Copyright (c) 2026 penspanic</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/penspanic/Mirrorgen</PackageProjectUrl>
        <RepositoryUrl>https://github.com/penspanic/Mirrorgen</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup Label="MinVer">
        <MinVerTagPrefix>v</MinVerTagPrefix>
        <MinVerDefaultPreReleaseIdentifiers>alpha.0</MinVerDefaultPreReleaseIdentifiers>
    </PropertyGroup>

    <ItemGroup Condition="'$(IsPackable)' != 'false'">
        <PackageReference Include="MinVer" PrivateAssets="all" />
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" Visible="false" />
    </ItemGroup>

</Project>
