<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <PackageId>Mirrorgen.MSBuild</PackageId>
        <Description>MSBuild target that runs the Mirrorgen transpiler during project build.</Description>
        <PackageTags>csharp;typescript;msbuild;mirrorgen</PackageTags>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <DevelopmentDependency>true</DevelopmentDependency>
        <NoPackageAnalysis>true</NoPackageAnalysis>
        <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddMSBuildAssetsToPackage</TargetsForTfmSpecificContentInPackage>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mirrorgen.Attributes\Mirrorgen.Attributes.csproj" />
        <ProjectReference Include="..\Mirrorgen.Core\Mirrorgen.Core.csproj" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Build.Framework" PrivateAssets="all" ExcludeAssets="runtime" />
        <PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
        <None Include="build\**" Pack="true" PackagePath="build\" />
    </ItemGroup>

    <Target Name="_AddMSBuildAssetsToPackage">
        <ItemGroup>
            <TfmSpecificPackageFile Include="$(OutputPath)\$(AssemblyName).dll" PackagePath="tasks/" />
            <TfmSpecificPackageFile Include="$(OutputPath)\Mirrorgen.Core.dll" PackagePath="tasks/" />
        </ItemGroup>
    </Target>

</Project>
