// Auto-generated by TsGen — DO NOT EDIT

export enum ConnectionState {
    Connecting = 0,
    Connected = 1,
    Disconnected = 2,
}

export interface JoinCellRequest {
    CellId: string;
    PlayerId: string;
}

export interface JoinCellResponse {
    CellId: string;
    State: ConnectionState;
    PlayerCount?: number | null;
    Reason?: string | null;
}

export interface CellSnapshot {
    Id: string;
    Captured: string;
    Members: string[];
    Counts: Record<string, number>;
}

export interface OperatorProfile {
    Name: string;
    LastJoin: JoinCellResponse;
}

export interface HostBanner {
    Title: string;
    Subtitle?: string | null;
    StateHistory: ConnectionState[];
}

